version: '3.8'

services:
  app:
    image: 'onboarding-api'
    build: .
    ports:
      - "8080:8080"
    container_name: onboarding-api
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    links:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: postgres-16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local