# postgres
database:
  url: jdbc:postgresql://localhost:5432/db
  username: postgres
  password: postgres
  name: db

spring:
  datasource:
    platform: postgres
    url: ${database.url}
    driverClassName: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop #none for flyway
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      format_sql: true
#  flyway:
#    user: ${database.username}
#    password: ${database.password}
#    url: ${SPRING_FLYWAY_URL} #when running from Intellij - set Run Configuration with Environment Variable - SPRING_FLYWAY_URL=jdbc:postgresql://localhost:5432/db