spring:
  profiles:
    active: postgres
  jackson:
    default-property-inclusion: non_empty

app:
  jwt-secret: "RALCARYCendULashWanalCOweineTIMATENtOrmARBIlbAgrAp"
  jwt-expiration-ms: 10800000 #3 Hrs
  countryAllowedList:
    - NL
    - BE
    - DE

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG