spring:
  profiles:
    active: postgres
  jackson:
    default-property-inclusion: non_empty

resilience4j:
  ratelimiter:
    instances:
      rateLimiter:
        limit-refresh-period: 1s
        limit-for-period: 2
        timeout-duration: 0s

app:
  jwt-secret: "SECRETSECRETSECRETSECRETSECRETSECRETSECRETSECRET"
  jwt-expiration-ms: 10800000 #3 Hrs
  countryAllowedList:
    - NL
    - BE
    - DE

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG