version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres-16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: 'onboarding-api'
    build: .
    ports:
      - "8080:8080"
    container_name: onboarding-api
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - SPRING_JPA_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    links:
      - postgres

volumes:
  db:
    driver: local